sudo: false
language: java
jdk: oraclejdk8
cache:
    directories:
        - .gradle
        - frontend/.gradle
        - frontend/node_modules
        - $HOME/.gradle
        - $HOME/.m2
branches:
    only: master
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
